development:
  bucket_name: <%= ENV['AMAZON_BUCKET'] %>
  access_key_id: <%= ENV['AMAZON_KEY'] %>
  secret_access_key: <%= ENV['AMAZON_SECRET'] %>
local_production:
  bucket_name: <%= ENV['AMAZON_BUCKET'] %>
  access_key_id: <%= ENV['AMAZON_KEY'] %>
  secret_access_key: <%= ENV['AMAZON_SECRET'] %>
test:
production:
  bucket_name: <%= ENV['AMAZON_BUCKET'] %>
  access_key_id: <%= ENV['AMAZON_KEY'] %>
  secret_access_key: <%= ENV['AMAZON_SECRET'] %>
sandbox:
  bucket_name: <%= ENV['AMAZON_BUCKET'] %>
  access_key_id: <%= ENV['AMAZON_KEY'] %>
  secret_access_key: <%= ENV['AMAZON_SECRET'] %>
